name: centos build workflows

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    container:
      image: almalinux:${{ matrix.version }}
      options: --platform ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          # AlmaLinux 8
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
            artifact: x86-64
            version: 8
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
            artifact: Arm64
            version: 8
          
          # AlmaLinux 9
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
            artifact: x86-64
            version: 9
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
            artifact: Arm64
            version: 9

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine


      - name: shell command
        run: cat /etc/redhat-release
          