name: debian build workflows

on:
  push:
    branches: 
      - develop
  
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        debian-version: [12]
        arch: [linux/amd64]

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build ${{ matrix.arch }} on debian ${{ matrix.debian-version }}
        run: |
          docker run --platform ${{ matrix.arch }} --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace debian:${{ matrix.debian-version }} /bin/sh -c '
            set -e
            apt update
            cd XEngine_SourceCode
            chmod 777 ./XEngine_BuildMake.sh
            ./XEngine_BuildMake.sh 
            make RELEASE=1
            make FLAGS=install
            make FLAGS=clean  '

      - name: Upload folder debian x86-64
        uses: actions/upload-artifact@v4
        with:
          name: XEngine_Debain_${{ matrix.debian-version }}_x86-64
          path: XEngine_Release/
          retention-days: 1