name: ios build workflows

on:
  push:
    branches: 
      - main

permissions:
  contents: read
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-15
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v6

      - name: vcpkg dependency repository
        uses: actions/checkout@v6
        with:
          repository: microsoft/vcpkg
          path: vcpkg           

      
      - name: vcpkg install
        run: |
            brew install cmake ninja pkg-config autoconf nasm
            cd vcpkg
            mkdir -p custom-triplets
            cat > custom-triplets/arm64-ios.cmake << 'EOF'
            set(VCPKG_TARGET_ARCHITECTURE arm64)
            set(VCPKG_CRT_LINKAGE dynamic)
            set(VCPKG_LIBRARY_LINKAGE static)
            set(VCPKG_CMAKE_SYSTEM_NAME iOS)
            set(VCPKG_OSX_ARCHITECTURES arm64)
            set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DENABLE_SRV=OFF)
            EOF

            ./bootstrap-vcpkg.sh
            ./vcpkg install 'mongo-c-driver:arm64-ios' --overlay-triplets=custom-triplets
      - name: Show vcpkg build logs on failure
        if: failure()
        run: |
          cat vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-out.log || true
          cat vcpkg/buildtrees/mongo-c-driver/config-arm64-ios-dbg-err.log || true