name: macos build workflows

on:
  push:
    branches:
      - 'main'
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-15
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v6
        with:
          ref: 'main'
        
      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: install xengine package
        run: |
            brew install mongo-c-driver@2 
            pkg-config --cflags mongoc2 

            brew --prefix mongo-c-driver@2
            ls $(brew --prefix mongo-c-driver@2)/include/

            echo -e "====================="
            ls -al /opt/homebrew/Cellar/mongo-c-driver/2.2.4/include/mongoc-2.2.4
            echo -e "====================="
            ls -al /opt/homebrew/opt/mongo-c-driver/mongoc-2.2.4
            
            