name: macos build workflows

on:
  push:
    branches: 
      - main
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
          - os: macos-14
          - os: macos-15
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV   
        
      - name: Set up Dependency Environment 
        run: |
            cd XEngine_Source
            chmod 777 *
            ./XEngine_LINEnv.sh -i 3