name: macos build workflows

on:
  push:
    branches: 
      - main
  
permissions:
  contents: read
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
          - os: macos-14
          - os: macos-15
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
            
      - name: install library
        if: matrix.os == 'macos-13'  
        run: |
            cd XEngine_Source
            chmod 777 ./XEngine_LINEnv.sh
            ./XEngine_LINEnv.sh -i 3
      - name: install library
        if: matrix.os == 'macos-14'  
        run: |
            latest_tag=$(git ls-remote --tags --sort="v:refname" https://github.com/libxengine/libxengine.git | awk '{print $2}' | sed 's/refs\/tags\///' | tail -n 1)
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_Mac_Arm64.zip
            unzip ./XEngine_Mac_Arm64.zip -d ./XEngine_Mac_Arm64
            cd XEngine_Mac_Arm64

            chmod 777 *
            ./XEngine_LINEnv.sh -i 3
      - name: install library
        if: matrix.os == 'macos-15'  
        run: |
            cd XEngine_Source
            chmod 777 ./XEngine_LINEnv.sh
            ./XEngine_LINEnv.sh -i 3