name: macos build workflows

on:
  push:
    branches:
      - 'main'
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-15
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v6
        with:
          ref: 'main'
        
      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: install xengine package
        run: |
            brew install tsduck
