name: macos build workflows

on:
  push:
    branches: 
      - main
  
permissions:
  contents: read
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
          - os: macos-14
          - os: macos-15
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
        
      - name: brew install
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            
      - name: install library
        if: matrix.os == 'macos-13'  
        run: |
            brew install mongo-c-driver@1
            ls -al /usr/local/opt
            echo -e "==========="
            ls -al /opt/local/opt/mongo-c-driver@1/include
      - name: install library
        if: matrix.os == 'macos-14'  
        run: |
            brew install mongo-c-driver@1
            ls -al /opt/homebrew/opt
            echo -e "==========="
            ls -al /opt/homebrew/opt/mongo-c-driver@1/include
      - name: install library
        if: matrix.os == 'macos-15'  
        run: |
            brew install mongo-c-driver@1
            ls -al /opt/homebrew/opt
            echo -e "==========="
            ls -al /opt/homebrew/opt/mongo-c-driver@1/include