name: macos build workflows

on:
  push:
    branches:
      - 'main'
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-15
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v6
        with:
          ref: 'main'
        
      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: install package
        run: |
            brew install opencv@4
            brew --prefix opencv@4
            ls -al /opt/homebrew/opt/opencv/include 
            ls -al /opt/homebrew/opt/opencv/include/opencv4 
            