name: rocky build workflows

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9

    steps:
       # 检出您的主仓库代码
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: install library
        run: |
            cd XEngine_SourceCode
            chmod 777 ./XEngine_BuildMake.sh
            ./XEngine_BuildMake.sh

      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg     

      - name: vcpkg install
        run: |
            cd vcpkg
            dnf install --allowerasing curl zip unzip tar autoconf libtool -y
            dnf install perl-IPC-Cmd perl-CPAN bison flex -y
            yes | cpan IPC::Cmd

            ./bootstrap-vcpkg.sh
            ./vcpkg install libiconv:x64-linux openssl:x64-linux curl[http2]:x64-linux mongo-c-driver[openssl]:x64-linux libmariadb[openssl]:x64-linux libpq[openssl]:x64-linux zlib:x64-linux minizip:x64-linux sqlite3:x64-linux nghttp2:x64-linux
            ./vcpkg install ffmpeg[all-nonfree,iconv,drawtext,fontconfig,amf,aom,ass,fdk-aac,ffmpeg,ffplay,ffprobe,nvcodec,opengl,opencl,qsv,x264,x265,webp]:x64-linux