name: rocky build workflows

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: install library
        run: |
            dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm -y
            dnf config-manager --enable crb
            dnf install git gcc g++ gdb make -y

      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg     

      - name: library install 
        run: |
            dnf install --allowerasing nasm curl zip unzip tar autoconf libtool python3-jinja2 diffutils -y
            dnf install mesa-libGL-devel libX11-devel libXft-devel libXext-devel wayland-devel libxkbcommon-devel mesa-libEGL-devel ibus-devel -y
            dnf install perl-IPC-Cmd perl-CPAN bison flex -y
            yes | cpan IPC::Cmd

      - name: vcpkg install
        run: |
            cp -rf ./vcpkg $HOME/vcpkg
            cd $HOME/vcpkg

            ./bootstrap-vcpkg.sh
            ././vcpkg install ffmpeg[x264,x265,postproc]:x64-linux-dynamic
            ls -al ./installed/x64-linux-dynamic/lib

      - name: build
        run: |
            g++ -Wall -std=c++20 -I /github/home/vcpkg/installed/x64-linux/include -L /github/home/vcpkg/installed/x64-linux/lib ConsoleApplication1.cpp -o ConsoleApplication1 \
            -lavformat -lavcodec -lavutil -lavdevice -lavfilter -lswscale -lswresample -lpostproc 
            ls -al
            chmod 777 ConsoleApplication1
            ./ConsoleApplication1
            g++ -Wall -fPIC -std=c++20 -o ConsoleApplication2.so ConsoleApplication2.cpp -shared -lavcodec -lavdevice -lavfilter -lavformat -lavutil -lswresample -lswscale -lpostproc -lx264 -lx265 -I /github/home/vcpkg/installed/x64-linux/include -L /github/home/vcpkg/installed/x64-linux/lib  -Wl,-rpath=../XEngine_BaseLib,--disable-new-dtags
            ls -al