name: rocky build workflows

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9

    steps:
       # 检出您的主仓库代码
      - name: Checkout main repository code
        uses: actions/checkout@v4
        with:
          ref: 'master'
        
       # 检出依赖的xengine仓库到指定的xengine目录
      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine

      - name: sub module checkout (opensource)
        run: |
            git submodule init
            git submodule update

      # 设置依赖库的环境变量
      - name: Set up Dependency rockylinux Environment
        run: |
            cd libxengine
            chmod 777 *
            sudo ./XEngine_LINEnv.sh -i 3
            cd ..