name: rocky build workflows

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: install library
        run: |
            dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm -y
            dnf config-manager --enable crb
            dnf install git gcc g++ gdb make nasm -y

      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg     

      - name: vcpkg install
        run: |
            cd vcpkg
            dnf install --allowerasing curl zip unzip tar autoconf libtool python3-jinja2 diffutils -y
            dnf install perl-IPC-Cmd perl-CPAN bison flex -y
            yes | cpan IPC::Cmd

            ./bootstrap-vcpkg.sh
            # ./vcpkg install libiconv:x64-linux openssl:x64-linux curl[http2]:x64-linux mongo-c-driver[openssl]:x64-linux libmariadb[openssl]:x64-linux libpq[openssl]:x64-linux zlib:x64-linux minizip:x64-linux sqlite3:x64-linux nghttp2:x64-linux
            ./vcpkg install ffmpeg[all-nonfree,iconv,drawtext,fontconfig,amf,aom,ass,fdk-aac,nvcodec,opencl,qsv,x264,x265,webp]:x64-linux 2>&1 | tee /tmp/vcpkg_install.log
            cat /tmp/vcpkg_install.log

      - name: Upload vcpkg install log
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg_logs
          path: |
            /__w/test/test/vcpkg/buildtrees/ffmpeg/build-x64-linux-rel-config.log
            /__w/test/test/vcpkg/buildtrees/ffmpeg/build-x64-linux-rel-out.log
          

