name: rockylinux build workflows

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ${{ matrix.runner }}
    container:
      image: rockylinux/rockylinux:${{ matrix.os_version }}
      options: --platform ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
            artifact: x86-64
            os_version: 9
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
            artifact: x86-64
            os_version: 10
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
            artifact: Arm64
            os_version: 9
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
            artifact: Arm64
            os_version: 10  

    steps:
       # 检出您的主仓库代码
      - name: Checkout main repository code
        uses: actions/checkout@v6

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
        
      - name: install library
        run: |
            dnf update -y
            dnf upgrade -y
            dnf install epel-release -y
            dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-10.noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-10.noarch.rpm -y
            dnf config-manager --enable crb

      - name: make amd64
        if: matrix.artifact == 'x86-64'
        run: | 
            cd XEngine_SourceCode
            make RELEASE=1
            make FLAGS=install
            make FLAGS=clean

      - name: make
        run: |
            dnf install mongo-c-driver-libs -y
            rpm -ql mongo-c-driver-libs