name: ubuntu Arm64 build workflows

on:
  push:
    branches: 
      - main


jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        architecture: [arm64]

    steps:
    - name: Checkout main repository code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      uses: docker/build-push-action@v26
      with:
        context: .
        platforms: linux/arm64
        push: false
        
    - name: Run commands
      run: |
        uname -a
        cat /etc/os-release
        
    - name: install library
      run: |
        chmod 777 ./XEngine_BuildMake.sh
        sudo ./XEngine_BuildMake.sh