name: ubuntu build workflows

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read
  
jobs:
  build:
    runs-on: 
      - ubuntu-24.04
      - ubuntu-22.04

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg     

      - name: vcpkg install
        run: |
            cp -rf ./vcpkg $HOME/vcpkg
            cd $HOME/vcpkg

            ./bootstrap-vcpkg.sh
            ././vcpkg install ffmpeg[all-nonfree,iconv,drawtext,fontconfig,amf,ass,fdk-aac,nvcodec,qsv,x264,x265]:x64-linux 2>&1 | tee /tmp/vcpkg_install.log
            cat /tmp/vcpkg_install.log

      - name: Upload vcpkg install log
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg_logs
          path: |
            /github/home/vcpkg/buildtrees/ffmpeg/build-x64-linux-rel-config.log
            /github/home/vcpkg/buildtrees/ffmpeg/build-x64-linux-rel-out.log
          

