name: ubuntu Arm64 build workflows

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/ubuntu

    steps:
    - name: Checkout main repository code
      uses: actions/checkout@v4
        
    - name: Run commands
      run: |
        uname -a
        cat /etc/os-release
        
    - name: install library
      run: |
        chmod 777 ./XEngine_BuildMake.sh
        sudo ./XEngine_BuildMake.sh