name: ubuntu build workflows

on:
  push:
    branches: [ "main1" ]
  
permissions:
  contents: read
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
          - os: ubuntu-24.04
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg     

      - name: vcpkg install
        run: |
            sudo apt install nasm autoconf automake libtool pkg-config -y
            cp -rf ./vcpkg $HOME/vcpkg
            cd $HOME/vcpkg

            ./bootstrap-vcpkg.sh
            ././vcpkg install ffmpeg[all-nonfree,iconv,drawtext,fontconfig,amf,ass,fdk-aac,nvcodec,qsv,x264,x265,postproc]:x64-linux
            ls -al ./installed/x64-linux/lib