name: Windows Arm64 build workflows

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: Set MSVC Build
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64

      - name: vcpkg dependency repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: vcpkg install 
        run: |
            cd vcpkg
            ./bootstrap-vcpkg.bat
            .\vcpkg.exe install libiconv:arm64-windows-static-md curl[http2]:arm64-windows-static-md mongo-c-driver[openssl]:arm64-windows-static-md libmariadb[core,openssl]:arm64-windows-static-md libpq[openssl]:arm64-windows-static-md zlib:arm64-windows-static-md minizip:arm64-windows-static-md sqlite3:arm64-windows-static-md nghttp2:arm64-windows-static-md ffmpeg[all]:arm64-windows-static-md --clean-after-build
            ./vcpkg.exe integrate install
        shell: pwsh